# Generated by Django 4.0.1 on 2022-03-30 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to=main.models.user_directory_path)),
                ('like_users', models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='font', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
