# Generated by Django 4.0.1 on 2022-03-31 06:08

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('Canceled', 'Canceled')], default='Canceled', max_length=10),
        ),
        migrations.AlterField(
            model_name='font',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.user_directory_path),
        ),
    ]
