# Generated by Django 4.0.1 on 2022-03-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_hwfuser_groups_hwfuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
