# Generated by Django 4.0.1 on 2022-03-31 05:56

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_hwfuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwfuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='hwfuser',
            name='name',
            field=models.CharField(default='Name', max_length=30),
        ),
    ]
