# Generated by Django 4.0.1 on 2022-03-31 05:57

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_hwfuser_profile_image_alter_hwfuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwfuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=user.models.user_directory_path),
        ),
    ]
